-- 1. Create user_roles table (Depdenency for RLS)
-- We use a flexible schema that works with both Supabase Auth (UUID) and Demo Mode (Email)
CREATE TABLE IF NOT EXISTS user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID UNIQUE,
    -- Link to auth.users if available
    email TEXT UNIQUE,
    -- Link to demo login if using that
    role TEXT NOT NULL CHECK (
        role IN (
            'admin',
            'official',
            'veedor',
            'arbitro',
            'delegado',
            'invitado'
        )
    ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Enable RLS
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
-- Policies for user_roles
CREATE POLICY "Public read user_roles" ON user_roles FOR
SELECT USING (true);
CREATE POLICY "Admin/Anon insert user_roles" ON user_roles FOR
INSERT WITH CHECK (true);
CREATE POLICY "Admin/Anon update user_roles" ON user_roles FOR
UPDATE USING (true);
-- Insert default demo roles if they don't exist
INSERT INTO user_roles (email, role)
VALUES ('admin@copadelta.com', 'admin'),
    ('veedor@copadelta.com', 'veedor'),
    ('arbitro@copadelta.com', 'arbitro') ON CONFLICT (email) DO NOTHING;
-- 2. Create groups table
CREATE TABLE IF NOT EXISTS groups (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Enable RLS for groups
ALTER TABLE groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON groups FOR
SELECT USING (true);
-- Allow admins/officials to modify groups. 
-- We use a simplified EXISTS check that works with our hybrid user_roles table
CREATE POLICY "Enable write for admins" ON groups FOR ALL USING (
    EXISTS (
        SELECT 1
        FROM user_roles
        WHERE (auth.uid() = user_roles.user_id) -- Check by Auth ID
            AND role = 'admin'
    )
);
-- 3. Add group_id to teams
ALTER TABLE teams
ADD COLUMN IF NOT EXISTS group_id UUID REFERENCES groups(id);