-- 1. Create Team Staff Table
CREATE TABLE IF NOT EXISTS public.team_staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES public.teams(id),
    profile_id UUID REFERENCES public.profiles(id),
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    role TEXT DEFAULT 'Delegado',
    -- 'Delegado', 'Dirigente', etc.
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Enable RLS
ALTER TABLE public.team_staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read team_staff" ON public.team_staff FOR
SELECT USING (true);
-- 2. Update Verification Trigger to handle 'official' role as Team Staff
CREATE OR REPLACE FUNCTION public.handle_user_verification() RETURNS trigger AS $$
DECLARE whitelist_entry record;
target_team_id bigint;
BEGIN -- A. Check Whitelist
SELECT * INTO whitelist_entry
FROM allowed_users
WHERE email = new.email;
IF whitelist_entry IS NOT NULL THEN -- 1. CREATE/UPDATE PROFILE
INSERT INTO public.profiles (id, email, full_name, cedula, phone, birth_date)
VALUES (
        new.id,
        new.email,
        whitelist_entry.full_name,
        whitelist_entry.cedula,
        whitelist_entry.phone,
        whitelist_entry.birth_date
    ) ON CONFLICT (id) DO
UPDATE
SET full_name = EXCLUDED.full_name,
    cedula = EXCLUDED.cedula,
    birth_date = EXCLUDED.birth_date;
-- 2. ASSIGN ROLE
INSERT INTO public.user_roles (user_id, email, role)
VALUES (
        new.id,
        new.email,
        COALESCE(whitelist_entry.assigned_role, 'fan')
    ) ON CONFLICT (user_id) DO
UPDATE
SET role = EXCLUDED.role;
-- 3. AUTO-ASSIGN TEAM (Logic for Players and Team Officials/Dirigentes)
IF whitelist_entry.assigned_team_name IS NOT NULL THEN -- Find Team ID
SELECT id INTO target_team_id
FROM teams
WHERE lower(name) = lower(whitelist_entry.assigned_team_name)
LIMIT 1;
IF target_team_id IS NOT NULL THEN -- Case A: It's a Player
IF whitelist_entry.assigned_role = 'player' THEN
UPDATE public.players
SET profile_id = new.id,
    email = new.email
WHERE team_id = target_team_id
    AND lower(name) = lower(whitelist_entry.full_name);
IF NOT FOUND THEN
INSERT INTO public.players (team_id, name, profile_id, email)
VALUES (
        target_team_id,
        whitelist_entry.full_name,
        new.id,
        new.email
    );
END IF;
-- Case B: It's a Team Official (Dirigente)
ELSIF whitelist_entry.assigned_role = 'official' THEN
INSERT INTO public.team_staff (team_id, profile_id, name, email, role)
VALUES (
        target_team_id,
        new.id,
        whitelist_entry.full_name,
        new.email,
        'Dirigente'
    ) ON CONFLICT (email) DO
UPDATE
SET profile_id = EXCLUDED.profile_id,
    team_id = EXCLUDED.team_id;
END IF;
END IF;
END IF;
ELSE -- B. RESTRICTED USER (Pending)
INSERT INTO public.user_roles (user_id, email, role)
VALUES (new.id, new.email, 'pending') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.profiles (id, email)
VALUES (new.id, new.email) ON CONFLICT (id) DO NOTHING;
END IF;
RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;