-- Tabla para gestionar roles vinculados a usuarios de Auth (o usuarios ficticios por ahora)
CREATE TABLE IF NOT EXISTS public.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    -- Puede ser NULL si usamos usuarios "dummy" sin auth real aún, o FK a auth.users
    email TEXT,
    -- Para mapear usuarios si no hay UUID consistente aun
    role TEXT NOT NULL CHECK (
        role IN (
            'admin',
            'veedor',
            'arbitro',
            'delegado',
            'invitado'
        )
    ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id),
    UNIQUE(email)
);
-- Habilitar RLS
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
-- Política: Lectura pública (para que la App sepa qué pintar)
CREATE POLICY "Public read user_roles" ON public.user_roles FOR
SELECT USING (true);
-- Política: Solo admins pueden editar roles (por ahora, anon puede si es demo mode, ajustar luego)
CREATE POLICY "Admin/Anon insert user_roles" ON public.user_roles FOR
INSERT WITH CHECK (true);
CREATE POLICY "Admin/Anon update user_roles" ON public.user_roles FOR
UPDATE USING (true);
-- Insertar roles iniciales para pruebas (basado en lo que hay en data.js/demo)
INSERT INTO public.user_roles (email, role)
VALUES ('admin@copadelta.com', 'admin'),
    ('veedor@copadelta.com', 'veedor') ON CONFLICT (email) DO
UPDATE
SET role = EXCLUDED.role;